# -----------------------------
# Discraft Plugin Configuration
# -----------------------------

# Discord Bot Token
# Your bot token is required for the bot to authenticate and connect to Discord.
token: "YOUR_BOT_TOKEN_HERE"

# Admins
# This list holds the Discord user IDs of the bot's administrators.
# These admins can control and manage the bot's functionality on the server.
admins:
  - "1092548532180877415"  # Example Discord user ID of an admin
  - "987654321098765432"  # Another example of an admin ID

# Main server
# The main server (or guild) that the discord bot belongs to.
guild_id: "GUILD_ID"

# Chat Channel
# This is the Discord channel ID where the chat from the Minecraft server will be sent.
chat_channel: "YOUR_CHAT_CHANNEL_ID"

# Console Channel
# This is the Discord channel ID where the console logs from the Minecraft server will be sent.
console_channel: "YOUR_CONSOLE_CHANNEL_ID"

# -----------------------------
# Additional Settings
# -----------------------------

# Bot status
# Leave as "nill" to view current minecraft server players
status: ""
activity_type: "1" # 0: Playing, 1: Listening, 2: Watching

# Whether to send Minecraft chat messages to Discord
chat_to_discord: true

# tip: starting your message with "!!" e.g "!!hey" the message will not be sent to discord/minecraft chat

# Whether to send Minecraft console messages to Discord
console_to_discord: true

# Whether to send discord messages to minecraft
discord_to_minecraft: true

# Events to send:
player_join: true
player_leave: true
player_death: true
player_advancements: true
server_on: true
server_off: true

# Other:
reactOnSuccess: true # Reacts with "📩" on a discord message when it successfully gets sent to the minecraft chat
debug: false
